### ISSUE TITLE
selected text has similar color in source control window

### ISSUE THREAD

**Issue by HaoboGu** [expo/vscode-expo-theme#22]
not select: 
<img width="317" alt="image" src="https://github.com/expo/vscode-expo-theme/assets/8640918/635cb693-ec91-4d7a-9ddd-a300484ce2bc">

selected:
<img width="304" alt="image" src="https://github.com/expo/vscode-expo-theme/assets/8640918/9539cc45-40fe-4407-9697-a4f3cc9017fa">

it's hard to distinguish selected text with normal text

**Comment by Simek** [comment]
Hey @HaoboGu, can you provide more details about the problem? Where exactly in the UI this problem occurs? What OS are you using?

I was not able to reproduce it on macOS, will be able to test this on Windows after the weekend.
<img width="396" alt="Screenshot 2023-10-07 at 09 32 13" src="https://github.com/expo/vscode-expo-theme/assets/719641/e72dc967-f46a-4d63-9003-60b65968ce33">

**Comment by HaoboGu** [comment]
@Simek I'm using macos as well. This issue can only be reproduced at source control tab on my machine:

<img width="420" alt="image" src="https://github.com/expo/vscode-expo-theme/assets/8640918/5f5abc53-5777-49eb-b047-8a6682657eb2">

<img width="383" alt="image" src="https://github.com/expo/vscode-expo-theme/assets/8640918/dbfff6f7-2b49-4edf-afad-4741c9673f3a">
